version: 2.1
orbs:
  node: circleci/node@4.3.0
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          install-yarn: true
          lts: true
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run build
          name: Run YARN build
workflows:
  node-tests:
    jobs:
      - test
