version: 2.1
orbs:
  node: circleci/node@4.5.1
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          install-yarn: true
          install-npm: false
          npm-version: lts
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run build
          name: Run YARN build
workflows:
  node-tests:
    jobs:
      - test
