version: 2.1
orbs:
  node: circleci/node@5.0.1
jobs:
  test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run build
          name: Run YARN build
workflows:
  node-tests:
    jobs:
      - test
